accounts/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name='accounts'

urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.welcome, name='welcome'),
    path('calendar/', views.calendar, name='Calendar'),
    path('identity/', views.identity, name='identity'),
    path('curriculum/', views.curriculum, name='curriculum'),
    path('attendance/', views.attendance, name='attendance'),
    path('notes/', views.notes, name='notes'),
]

collegebud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)

@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

blog/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import AuthenticationForm
from .forms import SignUpForm

def signup_view(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('accounts:login')
    else:
        form=SignUpForm()
    return render(request,'sign_up.html',{'form': form})

def login_view(request):
    if request.method == 'POST':
        form=AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request,user)
            return redirect('blog:welcome')
    else:
        form=AuthenticationForm()
    return render(request, 'login.html',{'form':form})

blog/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm

def welcome(request):
    return render(request, 'Welcome.html', {})

def calendar(request):
    return render(request, 'Calendar.html', {})

def identity(request):
    return render(request, 'identity.html', {})

def curriculum(request):
    return render(request, 'curriculum.html', {})

def attendance(request):
    return render(request, 'Attendance.html', {})

def notes(request):
    return render(request, 'notes.html', {})

blog/templates/Attendance.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
  <title>Untitled</title>
  <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets2/bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:400,700">
  <link rel="stylesheet" href="{% static 'assets2/fonts/ionicons.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets2/css/Features-Boxed.css' %}">
  <link rel="stylesheet" href="{% static 'assets2/css/Footer-Basic.css' %}">
  <link rel="stylesheet" href="{% static 'assets2/css/Footer-Dark.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
  <link rel="stylesheet" href="{% static 'assets2/css/Navigation-Clean.css' %}">
  <link rel="stylesheet" href="{% static 'assets2/css/styles.css' %}">
</head>

<body>
  <section class="features-icons bg-light text-center" id="top" style="background-color: #f8f9fa !important;">
    <nav class="navbar navbar-light navbar-expand-md navigation-clean">
        <div class="container"><a class="navbar-brand" href="{% url 'blog:welcome' %}">To Welcome Page</a><button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse"
                id="navcol-1">
                <ul class="nav navbar-nav ml-auto">
                  <li class="nav-item" role="presentation"><a class="nav-link" href="{% url 'blog:attendance' %}">Attendance</a></li>
                  <li class="nav-item" role="presentation"><a class="nav-link" href="{% url 'blog:Calendar' %}">Calendar</a></li>
                  <li class="nav-item" role="presentation"><a class="nav-link" href="#">Time Table</a></li>
                  <li class="nav-item dropdown"><a class="dropdown-toggle nav-link" data-toggle="dropdown" aria-expanded="false" href="#">Academic Stuff</a>
                      <div class="dropdown-menu" role="menu"><a class="dropdown-item" role="presentation" href="{% url 'blog:identity' %}">Identity Proof</a><a class="dropdown-item" role="presentation" href="{% url 'blog:curriculum' %}">Curriculum</a><a class="dropdown-item" role="presentation" href="{% url 'blog:notes' %}">Notes</a></div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</section>
  <div class="features-boxed">
    <div class="container">
      <div class="intro">
        <h2 class="text-center">Attendance Manager</h2>
        <p class="lead text-center text-primary d-xl-flex">We look after your attendance in classes so you can reach the required criterion to prevent a Z grade .&nbsp;</p>
      </div>
      <div class="row justify-content-center features">

        <div class="col-sm-6 col-md-5 col-lg-4 item">
          <div class="box" style="margin-top: 0px;">
            <h3 class="name">MA102</h3>
            <div class="border-primary" data-bs-hover-animate="pulse" style="margin-top: 10px;"><canvas id="chDonut1"></canvas></div>
            <p id="chPara1">Paragraph</p><button class="btn btn-success" type="button" style="margin-right: 20px;"onclick="present(chDonutData1,0,'chDonut1','chPara1')">Present</button><button class="btn btn-warning" onclick="absent(chDonutData1,0,'chDonut1','chPara1')" type="button">Absent</button>
          </div>
        </div>
        <div class="col-sm-6 col-md-5 col-lg-4 item">
          <div class="box">
            <h3 class="name">CSO 102</h3>
            <div class="border-primary" data-bs-hover-animate="pulse" style="margin-top: 10px;"><canvas id="chDonut2"></canvas></div>
            <p id="chPara2">Paragraph</p><button class="btn btn-success" type="button" style="margin-right: 20px;"onclick="present(chDonutData2,1,'chDonut2','chPara2')">Present</button><button class="btn btn-warning" onclick="absent(chDonutData2,1,'chDonut2','chPara2')" type="button" style="margin-right: 20px;">Absent</button>
          </div>
        </div>
        <div class="col-sm-6 col-md-5 col-lg-4 item">
          <div class="box">
            <h3 class="name">CSE 103</h3>
            <div class="border-primary" data-bs-hover-animate="pulse" style="margin-top: 10px;"><canvas id="chDonut3"></canvas></div>
            <p id="chPara3">Paragraph</p><button class="btn btn-success" type="button" style="margin-right: 20px;"onclick="present(chDonutData3,2,'chDonut3','chPara3')">Present</button><button class="btn btn-warning" onclick="absent(chDonutData3,2,'chDonut3','chPara3')" type="button" style="margin-right: 20px;">Absent</button>
          </div>
        </div>
        <div class="col-sm-6 col-md-5 col-lg-4 item">
          <div class="box">
            <h3 class="name">ME 104</h3>
            <div class="border-primary" data-bs-hover-animate="pulse" style="margin-top: 10px;"><canvas id="chDonut4"></canvas></div>
            <p id="chPara4">Paragraph</p><button class="btn btn-success" type="button" style="margin-right: 20px;"onclick="present(chDonutData4,3,'chDonut4','chPara4')">Present</button><button class="btn btn-warning" onclick="absent(chDonutData4,3,'chDonut4','chPara4')" type="button" style="margin-right: 20px;">Absent</button>
          </div>
        </div>
        <div class="col-sm-6 col-md-5 col-lg-4 item">
          <div class="box">
            <h3 class="name">EO 101</h3>
            <div class="border-primary" data-bs-hover-animate="pulse" style="margin-top: 10px;"><canvas id="chDonut5"></canvas></div>
            <p id="chPara5">Paragraph</p><button class="btn btn-success" type="button" style="margin-right: 20px;"onclick="present(chDonutData5,4,'chDonut5','chPara5')">Present</button><button class="btn btn-warning" onclick="absent(chDonutData5,4,'chDonut5','chPara5')" type="button" style="margin-right: 20px;">Absent</button>
          </div>
        </div>
        <div class="col-sm-6 col-md-5 col-lg-4 item">
          <div class="box">
            <h3 class="name">ED</h3>
            <div class="border-primary" data-bs-hover-animate="pulse" style="margin-top: 10px;"><canvas id="chDonut6"></canvas></div>
            <p id="chPara6">Paragraph</p><button class="btn btn-success" type="button" style="margin-right: 20px;"onclick="present(chDonutData6,5,'chDonut6','chPara6')">Present</button><button class="btn btn-warning" onclick="absent(chDonutData6,5,'chDonut6','chPara6')" type="button" style="margin-right: 20px;">Absent</button>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="footer-basic">
    <footer>
      <div class="social"><a href="#"><i class="icon ion-social-instagram"></i></a><a href="#"><i class="icon ion-social-snapchat"></i></a><a href="#"><i class="icon ion-social-twitter"></i></a><a href="#"><i class="icon ion-social-facebook"></i></a>
      </div>
      <ul class="list-inline">
        <li class="list-inline-item"><a href="#">Home</a></li>
        <li class="list-inline-item"><a href="#">Services</a></li>
        <li class="list-inline-item"><a href="#">About</a></li>
        <li class="list-inline-item"><a href="#">Terms</a></li>
        <li class="list-inline-item"><a href="#">Privacy Policy</a></li>
      </ul>
      <p class="copyright">Company Name © 2017</p>
    </footer>
  </div>
  <script src="{% static 'assets2/js/jquery.min.js' %}"></script>
  <script src="{% static 'assets2/bootstrap/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'assets2/js/chart.min.js' %}"></script>
  <script src="{% static 'assets2/js/bs-init.js' %}"></script>
  <script src="{% static 'Attendance.js' %}"></script>
</body>

</html>

blog/templates/Calendar.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'assets/css/Calendar.css' %}">
    <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic">
    <link rel="stylesheet" href="{% static 'assets/fonts/simple-line-icons.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/Navigation-Clean.css' %}">
    <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic">
    <link rel="stylesheet" href="{% static 'assets/fonts/simple-line-icons.min.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
    <link rel="stylesheet" href="{% static 'assets/css/Navigation-Clean.css' %}">
    <title>Calendar</title>
  </head>
  <body>
    <section class="features-icons bg-light text-center" id="top">
        <nav class="navbar navbar-light navbar-expand-md navigation-clean">
            <div class="container"><a class="navbar-brand" href="{% url 'blog:welcome' %}">To Welcome Page</a><button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse"
                    id="navcol-1">
                    <ul class="nav navbar-nav ml-auto">
                      <li class="nav-item" role="presentation"><a class="nav-link" href="{% url 'blog:attendance' %}">Attendance</a></li>
                      <li class="nav-item" role="presentation"><a class="nav-link" href="{% url 'blog:Calendar' %}">Calendar</a></li>
                      <li class="nav-item" role="presentation"><a class="nav-link" href="#">Time Table</a></li>
                      <li class="nav-item dropdown"><a class="dropdown-toggle nav-link" data-toggle="dropdown" aria-expanded="false" href="#">Academic Stuff</a>
                          <div class="dropdown-menu" role="menu"><a class="dropdown-item" role="presentation" href="{% url 'blog:identity' %}">Identity Proof</a><a class="dropdown-item" role="presentation" href="{% url 'blog:curriculum' %}">Curriculum</a><a class="dropdown-item" role="presentation" href="{% url 'blog:notes' %}">Notes</a></div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </section>

    <div class="container">
      <div class="calendar">
        <div class="front">
          <div class="current-date">
          </div>

          <div class="current-month">
            <ul class="week-days">
              <li>MON</li>
              <li>TUE</li>
              <li>WED</li>
              <li>THU</li>
              <li>FRI</li>
              <li>SAT</li>
              <li>SUN</li>
            </ul>

            <div class="weeks">
              <div class="first">
                <span class="last-month">26</span>
                <span class="last-month">27</span>
                <span class="last-month">28</span>
                <span class="last-month">29</span>
                <span class="last-month">30</span>
                <span class="last-month">31</span>
                <span id="01" onclick="giveId(this)">01</span>
              </div>

              <div class="second">
                <span id="02" onclick="giveId(02)">02</span>
                <span id="03" onclick="giveId(03)">03</span>
                <span id="04" onclick="giveId(04)">04</span>
                <span id="05" onclick="giveId(05)">05</span>
                <span id="06" onclick="giveId(06)">06</span>
                <span id="07" onclick="giveId(07)">07</span>
                <span id="08" onclick="giveId(08)">08</span>
              </div>

              <div class="third">
                <span id="09" onclick="giveId(09)">09</span>
                <span id="10" onclick="giveId(10)">10</span>
                <span id="11" onclick="giveId(11)">11</span>
                <span id="12" onclick="giveId(12)">12</span>
                <span id="13" onclick="giveId(13)">13</span>
                <span id="14" onclick="giveId(14)">14</span>
                <span id="15" onclick="giveId(15)">15</span>
              </div>

              <div class="fourth">
                <span id="16" onclick="giveId(16)">16</span>
                <span id="17" onclick="giveId(17)">17</span>
                <span id="18" onclick="giveId(18)">18</span>
                <span id="19" onclick="giveId(19)">19</span>
                <span id="20" onclick="giveId(20)">20</span>
                <span id="21" onclick="giveId(21)">21</span>
                <span id="22" onclick="giveId(22)">22</span>
              </div>

              <div class="fifth">
                <span id="23" onclick="giveId(23)">23</span>
                <span id="24" onclick="giveId(24)">24</span>
                <span id="25" onclick="giveId(25)">25</span>
                <span id="26" onclick="giveId(26)">26</span>
                <span id="27" onclick="giveId(27)">27</span>
                <span id="28" onclick="giveId(28)">28</span>
                <span id="29" onclick="giveId(29)" class="event">29</span>
              </div>
            </div>
          </div>
        </div>

        <div class="back">
          <input id ="what" placeholder="What's the event?">
          <div class="info">
            <div class="date">
              <p class="info-date">
              Date: Jan 15th, 2016
              </p>
            </div>
            <input placeholder="Time"></input>
            <div class="observations">
              <p>
                Task: <span>Be there 15 minutes earlier</span>
              </p>
            </div>
          </div>

          <div class="actions">
            <button class="save">
              Save <i class="ion-checkmark"></i>
            </button>
            <button class="dismiss">
              Dismiss <i class="ion-android-close"></i>
            </button>
          </div>
        </div>

      </div>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.js"></script>
    <script src="{% static 'assets/js/Calendar.js' %}"></script>
    <script src="{% static 'assets/js/jquery.min.js' %}"></script>
    <script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/bs-init.js' %}"></script>
  </body>
</html>

blog/templates/Welcome.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Welcome</title>
    <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic">
    <link rel="stylesheet" href="{% static 'assets/fonts/simple-line-icons.min.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
    <link rel="stylesheet" href="{% static 'assets/css/Navigation-Clean.css' %}">
</head>

<body>
    <section class="features-icons bg-light text-center">
        <nav class="navbar navbar-light navbar-expand-md navigation-clean">
            <div class="container"><a class="navbar-brand" href="#">College Bud</a><button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse"
                    id="navcol-1">
                    <ul class="nav navbar-nav ml-auto">
                        <li class="nav-item" role="presentation"><a class="nav-link" href="{% url 'blog:attendance' %}">Attendance</a></li>
                        <li class="nav-item" role="presentation"><a class="nav-link" href="{% url 'blog:Calendar' %}">Calendar</a></li>
                        <li class="nav-item" role="presentation"><a class="nav-link" href="#">Time Table</a></li>
                        <li class="nav-item dropdown"><a class="dropdown-toggle nav-link" data-toggle="dropdown" aria-expanded="false" href="#">Academic Stuff</a>
                            <div class="dropdown-menu" role="menu"><a class="dropdown-item" role="presentation" href="{% url 'blog:identity' %}">Identity Proof</a><a class="dropdown-item" role="presentation" href="{% url 'blog:curriculum' %}">Curriculum</a><a class="dropdown-item" role="presentation" href="{% url 'blog:notes' %}">Notes</a></div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            <div class="row">
                <div class="col-lg-4">
                    <div class="mx-auto features-icons-item mb-5 mb-lg-0 mb-lg-3">
                        <div class="d-flex features-icons-icon"><i class="icon-screen-desktop m-auto text-primary" data-bs-hover-animate="pulse" onclick="location.href='{% url 'blog:attendance' %}';"></i></div>
                        <h3>Attendance</h3>
                        <p class="lead mb-0">Check Your Attendance ratio&nbsp; so as to prevent a Z in your sheet : ) !</p>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="mx-auto features-icons-item mb-5 mb-lg-0 mb-lg-3">
                        <div class="d-flex features-icons-icon"><i class="icon-layers m-auto text-primary" data-bs-hover-animate="pulse" onclick="location.href='{% url 'blog:Calendar' %}';"></i></div>
                        <h3>Calendar</h3>
                        <p class="lead mb-0">Plan for upcoming Holidays and Events !</p>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="mx-auto features-icons-item mb-5 mb-lg-0 mb-lg-3">
                        <div class="d-flex features-icons-icon"><i class="icon-check m-auto text-primary" data-bs-hover-animate="pulse"></i></div>
                        <h3>Time Table</h3>
                        <p class="lead mb-0">No more issue of forgetting about classes we have it sorted for you !</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="showcase">
        <div class="container-fluid p-0">
            <div class="row no-gutters">
                <div class="col-lg-6 order-lg-2 text-white showcase-img" style="background-image:url(&quot;{% static 'assets/img/bg-showcase-3.jpg' %}&quot;);"><span></span></div>
                <div class="col-lg-6 my-auto order-lg-1 showcase-text">
                    <h2>Attendance</h2>
                    <p class="lead mb-0"><p class="lead mb-0">At times we miss our classes maybe because we were ill, had some other important task at
                    hand or maybe just too lazy to go to class but we have to ensure that our attendance is above
                    certain percentage. So at click of button you can add your day to day attendance and will warn you when the need arrives
                    of how many classes you need to attend.
                  </p>
                </div>
            </div>
            <div class="row no-gutters">
                <div class="col-lg-6 text-white showcase-img" style="background-image:url(&quot;{% static 'assets/img/bg-showcase-1.png' %}&quot;);"><span></span></div>
                <div class="col-lg-6 my-auto order-lg-1 showcase-text">
                    <h2>Calendar</h2>
                    <p class="lead mb-0">Which Fest is around the corner ? When are the Mid-Semester Examination starting ? What is the duration of Mid-Semester Break ? No need to bother your friends anymore
                    with these questions we have it all sorted for you. And not just that you can go on and create events of your own too. We will keep you updated with events happening in your institute.
                  </p>
                </div>
            </div>
            <div class="row no-gutters">
                <div class="col-lg-6 order-lg-2 text-white showcase-img" style="background-image:url(&quot;{% static 'assets/img/bg-showcase-2.jpg' %}&quot;);"><span></span></div>
                <div class="col-lg-6 my-auto order-lg-1 showcase-text">
                    <h2>Academic Stuff</h2>
                    <p class="lead mb-0">Looking around for basic stuffs like syllabus of a course or maybe a place of keep all your notes so that you can access them remotely
                    can be difficult at times. Also we need our identity with us to show it for entry into a pro-nite or for attendance purposes. So we bring these three pieces together
                  as a single set of academic tools.</p>
                </div>
            </div>
        </div>
    </section>
    <section class="testimonials text-center bg-light">
        <div class="container">
            <h2 class="mb-5">People Behind the App ...</h2>
            <div class="row">
                <div class="col-lg-3">
                    <div class="mx-auto testimonial-item mb-5 mb-lg-0"><img class="rounded-circle img-fluid mb-3" src="{% static 'assets/img/testimonials-1.jpg' %}">
                        <h5>Yash G.</h5>
                        <p class="font-weight-light mb-0">"He is a Full Stack Developer with some top notch algorithm skills.  Currently in First Year and pursuing B.Tech in Computer Science and Engineering from IIT BHU."</p>
                    </div>
                </div>
                <div class="col-lg-3">
                  <div class="mx-auto testimonial-item mb-5 mb-lg-0"><img id="img1" class="rounded-circle img-fluid mb-3" src="{% static 'assets/img/testimonials-3.jpg' %}">
                    <h5>Lakshya S.</h5>
                    <p class="font-weight-light mb-0">"He is a Front-End Web Developer and a persistent learner. Currently in First Year and pursuing B.Tech in Computer Science and Engineering from IIT BHU."</p>
                  </div>
                </div>
                <div class="col-lg-3">
                  <div class="mx-auto testimonial-item mb-5 mb-lg-0"><img class="rounded-circle img-fluid mb-3" src="{% static 'assets/img/testimonials-2.jpg' %}">
                    <h5>Shubhanshu S.</h5>
                    <p class="font-weight-light mb-0">"He is a Full-Stack Developer who belives in simplicity.  Currently in First Year and pursuing B.Tech in Computer Science and Engineering from IIT BHU."</p>
                  </div>
                </div>
                <div class="col-lg-3">
                    <div class="mx-auto testimonial-item mb-5 mb-lg-0"><img class="rounded-circle img-fluid mb-3" src="{% static 'assets/img/testimonials-4.jpg' %}">
                        <h5>Sanyu D.</h5>
                        <p class="font-weight-light mb-0">"She is a Front End Developer. Artist with pen and pixels too.  Currently in First Year and pursuing B.Tech in Civil Engineering from IIT BHU."</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <footer class="footer bg-light">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 my-auto h-100 text-center text-lg-left">
                    <ul class="list-inline mb-2">
                        <li class="list-inline-item"><a href="#">About</a></li>
                        <li class="list-inline-item"><span>⋅</span></li>
                        <li class="list-inline-item"><a href="#">Contact</a></li>
                        <li class="list-inline-item"><span>⋅</span></li>
                        <li class="list-inline-item"><a href="#">Terms of &nbsp;Use</a></li>
                        <li class="list-inline-item"><span>⋅</span></li>
                        <li class="list-inline-item"><a href="#">Privacy Policy</a></li>
                    </ul>
                </div>
                <div class="col-lg-6 my-auto h-100 text-center text-lg-right">
                    <ul class="list-inline mb-0">
                        <li class="list-inline-item"><a href="#"></a></li>
                        <li class="list-inline-item"><a href="#"></a></li>
                        <li class="list-inline-item"><a href="#"></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>
    <script src="{% static 'assets/js/jquery.min.js' %}"></script>
    <script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/bs-init.js' %}"></script>
</body>

</html>